# Generated by Django 3.0.5 on 2023-01-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='student_answer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
