# Generated by Django 3.2 on 2023-04-14 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_question_student_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='student_answer',
        ),
        migrations.CreateModel(
            name='student_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=600)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
            ],
        ),
    ]
